sudo: required
language: bash
dist: bionic

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get install git p7zip-full

script:
    - ./generate_patch.sh
    - cd out/ghctheme/firefox && 7z a -tzip firefox-ghc.zip * && cd ../../..
    - cd out/ghctheme && mv chrome chrome-ghc && 7z a -tzip chrome-ghc.zip chrome-ghc && cd ../..
    - cd out/darktheme/firefox && 7z a -tzip firefox-dark.zip * && cd ../../..
    - cd out/darktheme && mv chrome chrome-dark && 7z a -tzip chrome-dark.zip chrome-dark && cd ../..

deploy:
    provider: releases
    api_key: $TOKEN
    draft: true
    file:
        - "out/ghctheme/firefox/firefox-ghc.zip"
        - "out/darktheme/firefox/firefox-dark.zip"
        - "out/ghctheme/chrome-ghc.zip"
        - "out/darktheme/chrome-dark.zip"
    skip-cleanup: true
    on:
        tags: true
    name: Release $TRAVIS_TAG - $(date +'%Y.%m.%d')
